### ISSUE TITLE
Willow changes

### ISSUE THREAD

**Issue by JayLil07** [darionco/Warsak#11]
Willow is one of the last character we need change to fit our mod. Our plan for her is to make Bernie help her in battle. He can be summoned, similar to Don't Starve Together, but Willow doesn't need to be insane to do so, and he will only attack the enemy team. Bernie will not only need gold to be crafted, but also an external item, such as:
- A tallbird egg
- Manure
- Guano
- Etc.

**Comment by darionco** [comment]
I tried using bernie and it gets super complicated because he's really dumb. Fixing it would require to re-program its brain, we will be updating brains in the future but for now I think we're gonna go with making her use her lighter as a ranged weapon and an AoE attack.

**Comment by JayLil07** [comment]
Done! Will be released next update.
