### ISSUE TITLE
Wendy changes

### ISSUE THREAD

**Issue by JayLil07** [darionco/Warsak#12]
Wendy is part of the last few characters we're going to change. She is going to be able to place her sister, Abigail, somewhere on the map. She won't be to wander far from her spot, if at all, but will do the same damage, same health, etc. Along with needing gold to craft Abigail, Wendy will also need an external item, such as:
- A tallbird egg
- Manure
- Guano
- Etc.

**Comment by darionco** [comment]
We ended up implementing this as an AoE attack that uses Abigails health as a damage gauge This has open the door to new bugs and should be revisited in a new task.
