### ISSUE TITLE
"Boss" Fights

### ISSUE THREAD

**Issue by JayLil07** [darionco/Warsak#20]
As of right now, one boss fight is in the game, while the other is still a work in progress. Both need a little work and tweaking.

**The One in The Game**
_A little to easy:_ If you can kite, fighting these monsters are a piece of cake. You'll probably only need a helmet for the Varg/Deerclops. However, it does take a bit of time, and can be ruined if someone from the enemy team comes.

_Tentacle despawning:_ Sometimes, whether you're currently fighting the tentacle, or you've left it to fight later, it despawns, most likely because it's not in it's proper habitat in the swamp. The option we'll probably do to fix this is to take it out of the sequence and replace it with something else.

**The Work in Progress** 
_Monsters fighting each other:_ In order to make this one more difficult, we put multiple enemies together, so you'd have to fight them at the same time. A problem with this is that if you leave or are out of range, they begin attacking each other and even killing the Carrat at the end of the fight. There are 3 solutions to this problem:
- Finding enemies that don't attack each other
- Changing their behavior to stop them from attacking each other
- Only using one enemy at a time

_Each enemy killed drops an item:_ The more enemies in the fight you kill, the better loot they drop on death. You don't need to kill the boss completely if you only want the item it drops a few enemies in. However, the loot at the end will also be good. The sequence will be much longer and harder, though.

_Enemies at each dead end:_ This fight will take place in a maze. At the end of the maze, there'll be an arena where you fight the boss with all the loot. However, every time you hit a dead end in the maze, there'll be an enemy you need to fight. They'll be a little hard, but won't drop much good loot, so be careful where you go!

**Comment by darionco** [comment]
tentacle has been replaced by a mactusk

**Comment by darionco** [comment]
I think a better fix, that would also solve the issue of mobs spawning on the water, is to have a dedicated spawner that spawns new enemies once the last wave was killed.

**Comment by JayLil07** [comment]
Second boss fight complete
Made first boss fight harder
