### ISSUE TITLE
boss teleporting off the island

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#32]
during the mactusk phase, people will corner it and kill, making it spawn the clockwork knight on the ocean

**Comment by darionco** [comment]
#20 needs to be completed before this can be fixed

**Comment by JayLil07** [comment]
We're gonna fix this one by adding specific areas where mobs spawn in the arena and creating waves instead of spawning the next mob right where the other died.

**Comment by Thisguyizbad** [comment]
pretty sure this one is fixed
