### ISSUE TITLE
teleport with explorer with the sack on

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#34]
you can teleport with the lazy explorer while carrying the sack by dragging the item with your cursor and then teleporting there. We should remove the item all together in my opinion, as it would also solve the issue of Winona building catapults on the mid island. The walking cane is enough

**Comment by JayLil07** [comment]
It's been removed for now. You won't see it in the next update.

**Comment by darionco** [comment]
I think this should be a permanent change, let's close this issue for now.
