### ISSUE TITLE
Nerf Wigfrid and Wendy

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#36]
people are complaing about getting one shot by wendy, maybe reduce the damage to 125?

wigfrids buffs, namely lifesteal, are way too powerful, since you are practically indestructible with armor on. I put a suggestion for her in Character-changes

**Comment by darionco** [comment]
this is supposed to be a list of structured actionable tasks, please avoid writing suggestions here, we can discuss suggestion on discord. Closing.
