### ISSUE TITLE
Wolfgang balancing

### ISSUE THREAD

**Issue by JayLil07** [darionco/Warsak#4]
Wolfgang has been completely reworked, making him become slower and take less damage from enemies the more food he eats. Beause of this, he'll need a lot of tweaking to make him properly balanced. As of right now, he is too slow to be useful to the team, and often has to be left behind.

**Comment by darionco** [comment]
Changed wolfgang's values between 100 and max hunger.
```
damage absorption: -20% to +60%
speed multiplier: +5% to -20%
```
