### ISSUE TITLE
bee mines target team spiders

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#41]
bee mines placed by anyone will target all mobs, even that of your team

**Comment by darionco** [comment]
I think this one is by design, @JayLil07 ?

**Comment by Thisguyizbad** [comment]
bee mines also target bishops if placed close enough

**Comment by JayLil07** [comment]
Yeah, same with bramble traps. If you place them down, not only will your spiders trigger the trap, but it can also be reset by the enemy team. It's not game breaking, so it might take a while to be fixed.

**Comment by darionco** [comment]
the bramble traps are an issue, but we've removed bee mines from the game (we even removed the boss fights temporarily). We should create a new issue for the bramble traps
