### ISSUE TITLE
sudden death mode

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#43]
in order to not have games last as long, put a "sudden death" mode at the start of day 6. It's basically glorified summer, where people will overheat. Spiders will take 1-2 damage a second so we don't need to deal with the server crashing due to entities, along with other mobs like bishops and merms. Mobs that die this way don't drop gold, and wilson, webber, and woodie's beards don't become a hinderance in that they prevent you from losing heat. at the start of this mode, a polar light that never goes out will spawn at where the sack spawns, and items like chilled amulet, eyebrella, umbrella, and other summer gear can be bought at the shop.

**Comment by darionco** [comment]
sudden death mode is not gonna happen, it is a cheap way to try and balance the game that will leave players unsatisfied, we should find better ways to balance the game instead.

**Comment by JayLil07** [comment]
Having a sudden death mode is like having a time limit, you gotta work fast. Though I agree it's a way to stop games from dragging on for too long, it can also throw away all the work teams have done. I do like the idea of being able to purchase things for appropriate seasons, but as of right now it's probably not going to happen.
